[{"ContainerToolsException.Message":"[19384] Failed to execute script docker-compose","ContainerToolsException.ErrorCode":"DT1001","ContainerToolsException.StackTrace":"   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<ExecuteAsync>d__13.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 253\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerComposeClient.<DownAsync>d__8.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerComposeClient.cs:line 104\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.DockerWorkspace.<ComposeDownContainersAsync>d__32.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker\\DockerWorkspace.cs:line 425\r\n--- End of stack trace from previous location where exception was thrown ---\r\n   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)\r\n   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)\r\n   at Microsoft.Docker.BuildTasks.DockerBuildTask.<ExecuteAsync>d__34.MoveNext() in D:\\a\\_work\\1\\s\\src\\Microsoft.Docker.BuildTasks\\DockerBuildTask.cs:line 82","ContainerToolsException.HResult":"-2146233088","ContainerToolsException.CommandLine.Program":"docker-compose","ContainerToolsException.CommandLine.TelemetrySafeArguments":"","ContainerToolsException.CommandLine.ExitCode":"-1","ContainerToolsException.CommandLine.ErrorOutput":"Traceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 268, in _raise_for_status\r\n  File \"requests\\models.py\", line 941, in raise_for_status\r\nrequests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url: http+docker://localnpipe/version\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker\\api\\client.py\", line 214, in _retrieve_server_version\r\n  File \"docker\\api\\daemon.py\", line 181, in version\r\n  File \"docker\\api\\client.py\", line 274, in _result\r\n  File \"docker\\api\\client.py\", line 270, in _raise_for_status\r\n  File \"docker\\errors.py\", line 31, in create_api_error_from_http_exception\r\ndocker.errors.APIError: 500 Server Error for http+docker://localnpipe/version: Internal Server Error (\"b'i/o timeout'\")\r\nDuring handling of the above exception, another exception occurred:\r\nTraceback (most recent call last):\r\n  File \"docker-compose\", line 3, in <module>\r\n  File \"compose\\cli\\main.py\", line 81, in main\r\n  File \"compose\\cli\\main.py\", line 200, in perform_command\r\n  File \"compose\\cli\\command.py\", line 60, in project_from_options\r\n  File \"compose\\cli\\command.py\", line 152, in get_project\r\n  File \"compose\\cli\\docker_client.py\", line 41, in get_client\r\n  File \"compose\\cli\\docker_client.py\", line 170, in docker_client\r\n  File \"docker\\api\\client.py\", line 197, in __init__\r\n  File \"docker\\api\\client.py\", line 221, in _retrieve_server_version\r\ndocker.errors.DockerException: Error while fetching server API version: 500 Server Error for http+docker://localnpipe/version: Internal Server Error (\"b'i/o timeout'\")\r\n[19384] Failed to execute script docker-compose"}]